### ISSUE TITLE
"could not move bower_components" after "sails new test"

### ISSUE THREAD

**Issue by buxel** [chiefy/sails-generate-frontend-angular#3]
Hello,
iam trying to get this generator running and followed the instructions up to creating a new project. Then i get exceptions as seen below. I tried this both in cloud9 and nitrous.

```
$ sails new test
error: Couldn't move bower_components folder to /home/ubuntu/workspace/project/test/assets/vendor, try running `bower install`.
info: Bower done installing components to /home/ubuntu/workspace/project/test/assets/vendor

/home/ubuntu/.nvm/v0.10.30/lib/node_modules/bower/node_modules/q/q.js:126
                    throw e;
                          ^
Error: Callback was already called.
    at /home/ubuntu/.nvm/v0.10.30/lib/node_modules/sails/node_modules/async/lib/async.js:22:31
    at _normalizeCallback.callback.success (/home/ubuntu/.nvm/v0.10.30/lib/node_modules/sails/node_modules/reportback/node_modules/node-switchback/lib/normalize.js:33:26)
    at _switch (/home/ubuntu/.nvm/v0.10.30/lib/node_modules/sails/node_modules/reportback/node_modules/node-switchback/lib/factory.js:34:26)
    at /home/ubuntu/.nvm/v0.10.30/lib/node_modules/sails/node_modules/async/lib/async.js:142:25
    at _normalizeCallback.callback.success (/home/ubuntu/.nvm/v0.10.30/lib/node_modules/sails/node_modules/reportback/node_modules/node-switchback/lib/normalize.js:33:26)
    at _switch (/home/ubuntu/.nvm/v0.10.30/lib/node_modules/sails/node_modules/reportback/node_modules/node-switchback/lib/factory.js:34:26)
    at _normalizeCallback.callback.success (/home/ubuntu/.nvm/v0.10.30/lib/node_modules/sails/node_modules/reportback/node_modules/node-switchback/lib/normalize.js:33:26)
    at _switch (/home/ubuntu/.nvm/v0.10.30/lib/node_modules/sails/node_modules/reportback/node_modules/node-switchback/lib/factory.js:34:26)
    at Logger.<anonymous> (/home/ubuntu/.nvm/v0.10.30/lib/node_modules/sails-generate-frontend-angular/lib/after.js:22:13)
    at Logger.emit (events.js:95:17)
```

**Comment by buxel** [comment]
There are so many sails/angular integration examples and modules out there so i wonder which one is the way to go now. There should be a little hint somewhere in the sailsjs documentation.

//sorry, i accidently closed this issue with this comment.

**Comment by buxel** [comment]
My guess is that there are two things wrong. One is that moving the bower components fail for me and number two is how this failure is handled here:
https://github.com/chiefy/sails-generate-frontend-angular/blob/master/lib/after.js

```
.on('end', function() {
        var destination = scope.rootPath + '/assets/vendor';
        try {
            fs.renameSync(fs.realpathSync(scope.rootPath + '/bower_components'), destination);
        } catch(ex) {
            cb.log.error('Couldn\'t move bower_components folder to ' + destination + ', try running `bower install`.');
            cb();
        }
        cb.log.info('Bower done installing components to ' + fs.realpathSync(destination));
        cb();
    })
```

if  fs.renameSync fails, the exception is called and logged. After that the callback cb() gets called. 
It should either not call cb() in the catch block, or return after calling it because some lines below, after cb.log.info() , it gets called again.

I favor returning because printing 'Bower done installing components' after there was an exception just seems odd.

**Comment by buxel** [comment]
Iam not quite sure why the moving is necessary at all. in .bowerrc the component folder is already configured as /asset/vendor so my guess is that the source (/bower_components) it tries to move from does not exist.

**Comment by chiefy** [comment]
Hey @ChaosD , sorry I am really busy w/ my day job, but there was a reason why I was trying to move the `bower_components` folder. I believe there was an issue with using `.bowerrc` progamatically. I think they may have fixed the issue, so now it's actually installing bower components to the `vendor` folder. And you're correct, inside that catch it should be `return cb();` I will try to patch it this weekend. Thanks!

**Comment by buxel** [comment]
I already tried commenting the callback out and then it creates a new project without errors. When I try to open it after lifting,  all I get is a white page. 
Is that normal or should I get the sails default page? I suspect my setup might be a little messed up. 
Could you test it and tell me what you get? 
Thank you!

**Comment by spunkedy** [comment]
Your suggestion ChaosD worked for me. I haven't figured out if I am going to use this kickstarter yet, but at least got past that issue

**Comment by buxel** [comment]
@spunkedy , after creating a new app with this generator and lifting it, do you get more than a blank page? After several attempts, this is still all i get :/

**Comment by spunkedy** [comment]
No, if you look at my pull request I have 2 screen shots. 

Here is the exact commands I ran:

```
imac:sails ebond$ sails new asdf
error: Couldn't move bower_components folder to /Users/ebond/work/withgod/source/sails/asdf/assets/vendor, try running `bower install`.
info: Bower done installing components to /Users/ebond/work/withgod/source/sails/asdf/assets/vendor
info: Created a new Sails app `asdf`!
imac:sails ebond$ cd asdf
imac:asdf ebond$ bower install
imac:asdf ebond$ ls
Gruntfile.js    README.md   api     app.js      assets      bower.json  config      node_modules    package.json    tasks       views
imac:asdf ebond$ find ./ | grep bower
.//.bowerrc
.//assets/vendor/angular/.bower.json
.//assets/vendor/angular/bower.json
.//assets/vendor/angular-classy/.bower.json
.//assets/vendor/angular-classy/bower.json
.//assets/vendor/angular-ui-router/.bower.json
.//assets/vendor/angular-ui-router/bower.json
.//assets/vendor/lodash/.bower.json
.//assets/vendor/lodash/bower.json
.//assets/vendor/restangular/.bower.json
.//assets/vendor/restangular/bower.json
.//bower.json
imac:asdf ebond$ cd assets/vendor/
imac:vendor ebond$ bower install
bower                           ENOENT No bower.json present
imac:vendor ebond$ cd angular
imac:angular ebond$ bower install
imac:angular ebond$ cd ..
imac:vendor ebond$ cd ..
imac:assets ebond$ bower install
bower                           ENOENT No bower.json present
imac:assets ebond$ cd ..
imac:asdf ebond$ bower install
imac:asdf ebond$ find ./ | grep bower
.//.bowerrc
.//assets/vendor/angular/.bower.json
.//assets/vendor/angular/bower.json
.//assets/vendor/angular-classy/.bower.json
.//assets/vendor/angular-classy/bower.json
.//assets/vendor/angular-ui-router/.bower.json
.//assets/vendor/angular-ui-router/bower.json
.//assets/vendor/lodash/.bower.json
.//assets/vendor/lodash/bower.json
.//assets/vendor/restangular/.bower.json
.//assets/vendor/restangular/bower.json
.//bower.json
imac:asdf ebond$ sails generate api movie
info: Created a new api!
imac:asdf ebond$ sails lift

info: Starting app...

-----------------------------------------------------------------

 Excuse my interruption, but it looks like this app
 does not have a project-wide "migrate" setting configured yet.
 (perhaps this is the first time you're lifting it with models?)

 In short, this setting controls whether/how Sails will attempt to automatically
 rebuild the tables/collections/sets/etc. in your database schema.
 You can read more about the "migrate" setting here:
 http://sailsjs.org/#/documentation/concepts/ORM/model-settings.html?q=migrate

 In a production environment (NODE_ENV==="production") Sails always uses
 migrate:"safe" to protect inadvertent deletion of your data.
 However during development, you have a few other options for convenience:

 1. safe  - never auto-migrate my database(s). I will do it myself (by hand) 
 2. alter - auto-migrate, but attempt to keep my existing data (experimental)
 3. drop  - wipe/drop ALL my data and rebuild models every time I lift Sails

What would you like Sails to do?

info: To skip this prompt in the future, set `sails.config.models.migrate`.
info: (conventionally, this is done in `config/models.js`)

warn: ** DO NOT CHOOSE "2" or "3" IF YOU ARE WORKING WITH PRODUCTION DATA **

prompt: ?:  3

 Temporarily using `sails.config.models.migrate="drop"...
 (press CTRL+C to cancel-- continuing lift automatically in 0.5 seconds...)

info: 
info: 
info:    Sails              <|
info:    v0.10.5             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info: 
info: Server lifted in `/Users/ebond/work/withgod/source/sails/asdf`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Mon Oct 06 2014 03:26:45 GMT-0500 (CDT)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------
```

**Comment by spunkedy** [comment]
![screen shot 2014-10-06 at 3 30 55 am](https://cloud.githubusercontent.com/assets/690735/4526465/84e1887e-4d5f-11e4-8507-4a9707734c9d.png)

**Comment by buxel** [comment]
Thank you, after several attempts i can confirm it is working as shown in your screenshots. For some reason my setup did not pick up globally installed modules sometimes.

**Comment by spunkedy** [comment]
yeah, I renamed mine, and then went into the source and did a npm link. Feel free to make your own pull request for credit since you are the one that found the issue, I just verified your changeset.

**Comment by buxel** [comment]
I will try that... witness my first pull request (attempt)! :smile:

**Comment by avimar** [comment]
I had this problem too. The fix wasn't pushed to NPM, I had to use:
`sudo npm install -g git://github.com/chiefy/sails-generate-frontend-angular.git`

**Comment by chiefy** [comment]
@avimar Sorry, I forgot to tag and publish to npm. I just did, so you should be all set to use @0.0.2 or latest.
